INSERT INTO `countries` (`name`, `iso_code_2`, `iso_code_3`, `isd_code`, `created_by`, `updated_by`) VALUES
('Afghanistan', 'AF', 'AFG', '93', 1, NULL),
('Albania', 'AL', 'ALB', '355', 1, NULL),
('Algeria', 'DZ', 'DZA', '213', 1, NULL),
('American Samoa', 'AS', 'ASM', '1684', 1, NULL),
('Andorra', 'AD', 'AND', '376', 1, NULL),
('Angola', 'AO', 'AGO', '244', 1, NULL),
('Anguilla', 'AI', 'AIA', '1264', 1, NULL),
('Antarctica', 'AQ', 'ATA', '672', 1, NULL),
('Antigua and Barbuda', 'AG', 'ATG', '1268', 1, NULL),
('Argentina', 'AR', 'ARG', '54', 1, NULL),
('Armenia', 'AM', 'ARM', '374', 1, NULL),
('Aruba', 'AW', 'ABW', '297', 1, NULL),
('Australia', 'AU', 'AUS', '61', 1, NULL),
('Austria', 'AT', 'AUT', '43', 1, NULL),
('Azerbaijan', 'AZ', 'AZE', '994', 1, NULL),
('Bahamas', 'BS', 'BHS', '1242', 1, NULL),
('Bahrain', 'BH', 'BHR', '973', 1, NULL),
('Bangladesh', 'BD', 'BGD', '880', 1, NULL),
('Barbados', 'BB', 'BRB', '1246', 1, NULL),
('Belarus', 'BY', 'BLR', '375', 1, NULL),
('Belgium', 'BE', 'BEL', '32', 1, NULL),
('Belize', 'BZ', 'BLZ', '501', 1, NULL),
('Benin', 'BJ', 'BEN', '229', 1, NULL),
('Bermuda', 'BM', 'BMU', '1441', 1, NULL),
('Bhutan', 'BT', 'BTN', '975', 1, NULL),
('Bosnia and Herzegovina', 'BA', 'BIH', '387', 1, NULL),
('Botswana', 'BW', 'BWA', '267', 1, NULL),
('Brazil', 'BR', 'BRA', '55', 1, NULL),
('Brunei Darussalam', 'BN', 'BRN', '673', 1, NULL),
('Bulgaria', 'BG', 'BGR', '359', 1, NULL),
('Burkina Faso', 'BF', 'BFA', '226', 1, NULL),
('Burundi', 'BI', 'BDI', '257', 1, NULL),
('Cambodia', 'KH', 'KHM', '855', 1, NULL),
('Cameroon', 'CM', 'CMR', '237', 1, NULL),
('Cape Verde', 'CV', 'CPV', '238', 1, NULL),
('Chad', 'TD', 'TCD', '235', 1, NULL),
('Chile', 'CL', 'CHL', '56', 1, NULL),
('China', 'CN', 'CHN', '86', 1, NULL),
('Colombia', 'CO', 'COL', '57', 1, NULL),
('Comoros', 'KM', 'COM', '269', 1, NULL),
('Congo', 'CG', 'COG', '242', 1, NULL),
('Costa Rica', 'CR', 'CRI', '506', 1, NULL),
('Croatia', 'HR', 'HRV', '385', 1, NULL),
('Cuba', 'CU', 'CUB', '53', 1, NULL),
('CuraÃ§ao', 'CW', 'CUW', '599', 1, NULL),
('Cyprus', 'CY', 'CYP', '357', 1, NULL),
('Denmark', 'DK', 'DNK', '45', 1, NULL),
('Djibouti', 'DJ', 'DJI', '253', 1, NULL),
('Dominica', 'DM', 'DMA', '1767', 1, NULL),
('Ecuador', 'EC', 'ECU', '593', 1, NULL),
('Egypt', 'EG', 'EGY', '20', 1, NULL),
('El Salvador', 'SV', 'SLV', '503', 1, NULL),
('Equatorial Guinea', 'GQ', 'GNQ', '240', 1, NULL),
('Eritrea', 'ER', 'ERI', '291', 1, NULL),
('Estonia', 'EE', 'EST', '372', 1, NULL),
('Ethiopia', 'ET', 'ETH', '251', 1, NULL),
('Fiji', 'FJ', 'FJI', '679', 1, NULL),
('Finland', 'FI', 'FIN', '358', 1, NULL),
('France', 'FR', 'FRA', '33', 1, NULL),
('French Guiana', 'GF', 'GUF', '594', 1, NULL),
('French Polynesia', 'PF', 'PYF', '689', 1, NULL),
('Gabon', 'GA', 'GAB', '241', 1, NULL),
('Gambia', 'GM', 'GMB', '220', 1, NULL),
('Georgia', 'GE', 'GEO', '995', 1, NULL),
('Germany', 'DE', 'DEU', '49', 1, NULL),
('Ghana', 'GH', 'GHA', '233', 1, NULL),
('Gibraltar', 'GI', 'GIB', '350', 1, NULL),
('Greece', 'GR', 'GRC', '30', 1, NULL),
('Greenland', 'GL', 'GRL', '299', 1, NULL),
('Grenada', 'GD', 'GRD', '1473', 1, NULL),
('Guam', 'GU', 'GUM', '1671', 1, NULL),
('Guatemala', 'GT', 'GTM', '502', 1, NULL),
('Guinea', 'GN', 'GIN', '224', 1, NULL),
('Guinea-Bissau', 'GW', 'GNB', '245', 1, NULL),
('Guyana', 'GY', 'GUY', '592', 1, NULL),
('Haiti', 'HT', 'HTI', '509', 1, NULL),
('Holy See (Vatican City State)', 'VA', 'VAT', '3906', 1, NULL),
('Honduras', 'HN', 'HND', '504', 1, NULL),
('Hong Kong', 'HK', 'HKG', '852', 1, NULL),
('Hungary', 'HU', 'HUN', '36', 1, NULL),
('Iceland', 'IS', 'ISL', '354', 1, NULL),
('India', 'IN', 'IND', '91', 1, NULL),
('Indonesia', 'ID', 'IDN', '62', 1, NULL),
('Iraq', 'IQ', 'IRQ', '964', 1, NULL),
('Ireland', 'IE', 'IRL', '353', 1, NULL),
('Israel', 'IL', 'ISR', '972', 1, NULL),
('Italy', 'IT', 'ITA', '39', 1, NULL),
('Jamaica', 'JM', 'JAM', '1876', 1, NULL),
('Japan', 'JP', 'JPN', '81', 1, NULL),
('Jordan', 'JO', 'JOR', '962', 1, NULL),
('Kazakhstan', 'KZ', 'KAZ', '7', 1, NULL),
('Kenya', 'KE', 'KEN', '254', 1, NULL),
('Kiribati', 'KI', 'KIR', '686', 1, NULL),
('Kuwait', 'KW', 'KWT', '965', 1, NULL),
('Kyrgyzstan', 'KG', 'KGZ', '996', 1, NULL),
('Latvia', 'LV', 'LVA', '371', 1, NULL),
('Lebanon', 'LB', 'LBN', '961', 1, NULL),
('Lesotho', 'LS', 'LSO', '266', 1, NULL),
('Liberia', 'LR', 'LBR', '231', 1, NULL),
('Libya', 'LY', 'LBY', '218', 1, NULL),
('Liechtenstein', 'LI', 'LIE', '423', 1, NULL),
('Lithuania', 'LT', 'LTU', '370', 1, NULL),
('Luxembourg', 'LU', 'LUX', '352', 1, NULL),
('Macao', 'MO', 'MAC', '853', 1, NULL),
('Madagascar', 'MG', 'MDG', '261', 1, NULL),
('Malawi', 'MW', 'MWI', '265', 1, NULL),
('Malaysia', 'MY', 'MYS', '60', 1, NULL),
('Maldives', 'MV', 'MDV', '960', 1, NULL),
('Mali', 'ML', 'MLI', '223', 1, NULL),
('Malta', 'MT', 'MLT', '356', 1, NULL),
('Martinique', 'MQ', 'MTQ', '596', 1, NULL),
('Mauritania', 'MR', 'MRT', '222', 1, NULL),
('Mauritius', 'MU', 'MUS', '230', 1, NULL),
('Mayotte', 'YT', 'MYT', '262', 1, NULL),
('Mexico', 'MX', 'MEX', '52', 1, NULL),
('Monaco', 'MC', 'MCO', '377', 1, NULL),
('Mongolia', 'MN', 'MNG', '976', 1, NULL),
('Montenegro', 'ME', 'MNE', '382', 1, NULL),
('Montserrat', 'MS', 'MSR', '1664', 1, NULL),
('Morocco', 'MA', 'MAR', '212', 1, NULL),
('Mozambique', 'MZ', 'MOZ', '258', 1, NULL),
('Myanmar', 'MM', 'MMR', '95', 1, NULL),
('Namibia', 'NA', 'NAM', '264', 1, NULL),
('Nauru', 'NR', 'NRU', '674', 1, NULL),
('Nepal', 'NP', 'NPL', '977', 1, NULL),
('Netherlands', 'NL', 'NLD', '31', 1, NULL),
('New Caledonia', 'NC', 'NCL', '687', 1, NULL),
('New Zealand', 'NZ', 'NZL', '64', 1, NULL),
('Nicaragua', 'NI', 'NIC', '505', 1, NULL),
('Niger', 'NE', 'NER', '227', 1, NULL),
('Nigeria', 'NG', 'NGA', '234', 1, NULL),
('Niue', 'NU', 'NIU', '683', 1, NULL),
('Norway', 'NO', 'NOR', '47', 1, NULL),
('Oman', 'OM', 'OMN', '968', 1, NULL),
('Pakistan', 'PK', 'PAK', '92', 1, NULL),
('Palau', 'PW', 'PLW', '680', 1, NULL),
('Panama', 'PA', 'PAN', '507', 1, NULL),
('Papua New Guinea', 'PG', 'PNG', '675', 1, NULL),
('Paraguay', 'PY', 'PRY', '595', 1, NULL),
('Peru', 'PE', 'PER', '51', 1, NULL),
('Philippines', 'PH', 'PHL', '63', 1, NULL),
('Pitcairn', 'PN', 'PCN', '870', 1, NULL),
('Poland', 'PL', 'POL', '48', 1, NULL),
('Portugal', 'PT', 'PRT', '351', 1, NULL),
('Qatar', 'QA', 'QAT', '974', 1, NULL),
('Romania', 'RO', 'ROU', '40', 1, NULL),
('Rwanda', 'RW', 'RWA', '250', 1, NULL),
('Saint Kitts and Nevis', 'KN', 'KNA', '1869', 1, NULL),
('Saint Lucia', 'LC', 'LCA', '1758', 1, NULL),
('Saint Martin (French part)', 'MF', 'MAF', '590', 1, NULL),
('Saint Pierre and Miquelon', 'PM', 'SPM', '508', 1, NULL),
('Saint Vincent and the Grenadines', 'VC', 'VCT', '1784', 1, NULL),
('Samoa', 'WS', 'WSM', '685', 1, NULL),
('San Marino', 'SM', 'SMR', '378', 1, NULL),
('Sao Tome and Principe', 'ST', 'STP', '239', 1, NULL),
('Saudi Arabia', 'SA', 'SAU', '966', 1, NULL),
('Senegal', 'SN', 'SEN', '221', 1, NULL),
('Seychelles', 'SC', 'SYC', '248', 1, NULL),
('Sierra Leone', 'SL', 'SLE', '232', 1, NULL),
('Singapore', 'SG', 'SGP', '65', 1, NULL),
('Sint Maarten (Dutch part)', 'SX', 'SXM', '1721', 1, NULL),
('Slovakia', 'SK', 'SVK', '421', 1, NULL),
('Slovenia', 'SI', 'SVN', '386', 1, NULL),
('Somalia', 'SO', 'SOM', '252', 1, NULL),
('South Africa', 'ZA', 'ZAF', '27', 1, NULL),
('South Georgia and the South Sandwich Islands', 'GS', 'SGS', '500', 1, NULL),
('South Sudan', 'SS', 'SSD', '211', 1, NULL),
('Spain', 'ES', 'ESP', '34', 1, NULL),
('Sri Lanka', 'LK', 'LKA', '94', 1, NULL),
('Sudan', 'SD', 'SDN', '249', 1, NULL),
('Suriname', 'SR', 'SUR', '597', 1, NULL),
('Swaziland', 'SZ', 'SWZ', '268', 1, NULL),
('Sweden', 'SE', 'SWE', '46', 1, NULL),
('Switzerland', 'CH', 'CHE', '41', 1, NULL),
('Tajikistan', 'TJ', 'TJK', '992', 1, NULL),
('Thailand', 'TH', 'THA', '66', 1, NULL),
('Timor-Leste', 'TL', 'TLS', '670', 1, NULL),
('Togo', 'TG', 'TGO', '228', 1, NULL),
('Tokelau', 'TK', 'TKL', '690', 1, NULL),
('Tonga', 'TO', 'TON', '676', 1, NULL),
('Trinidad and Tobago', 'TT', 'TTO', '1868', 1, NULL),
('Tunisia', 'TN', 'TUN', '216', 1, NULL),
('Turkey', 'TR', 'TUR', '90', 1, NULL),
('Turkmenistan', 'TM', 'TKM', '993', 1, NULL),
('Tuvalu', 'TV', 'TUV', '688', 1, NULL),
('Uganda', 'UG', 'UGA', '256', 1, NULL),
('Ukraine', 'UA', 'UKR', '380', 1, NULL),
('United Arab Emirates', 'AE', 'ARE', '971', 1, NULL),
('United Kingdom', 'GB', 'GBR', '44', 1, NULL),
('United States', 'US', 'USA', '1', 1, NULL),
('Uruguay', 'UY', 'URY', '598', 1, NULL),
('Uzbekistan', 'UZ', 'UZB', '998', 1, NULL),
('Vanuatu', 'VU', 'VUT', '678', 1, NULL),
('Viet Nam', 'VN', 'VNM', '84', 1, NULL),
('Wallis and Futuna', 'WF', 'WLF', '681', 1, NULL),
('Yemen', 'YE', 'YEM', '967', 1, NULL),
('Zambia', 'ZM', 'ZMB', '260', 1, NULL),
('Zimbabwe', 'ZW', 'ZWE', '263', 1, NULL);
